### ISSUE TITLE
active_callback for 'image' and 'upload' options

### ISSUE THREAD

**Issue by RescueThemes** [devinsays/customizer-library#19]
I'm trying to use:

```
'active_callback' => 'is_front_page',
```

It doesn't seem to work for image and upload options though. Would it just be a matter of adding active_callback to the options switch? 

https://github.com/devinsays/customizer-library/blob/master/extensions/interface.php#L81-L109

**Comment by devinsays** [comment]
Yep, everything appears to be working now. Closing issue.
