### ISSUE TITLE
Add custom control for additional html & help text

### ISSUE THREAD

**Issue by bghouse** [devinsays/customizer-library#20]
Add an additional control that would allow for additional html - e.g. A heading or description, a line, etc.

An example would be something like this:  http://coreymckrill.com/blog/2014/01/09/adding-arbitrary-html-to-a-wordpress-theme-customizer-section/

I believe this is the last piece keeping folks from embracing the customizer for all theme options - as currently we have no good way add additional help text and communicate to end users.  Corey's article above is exactly the situation I just ran into.  Panels might help, but those are not in the library either at this time.

**Comment by andrezrv** [comment]
+1 to this. A text-only control would also be great.

**Comment by jamigibbs** [comment]
Just wanted to share how I'm doing this. Not sure if a pull request is necessary:

Add a new file to the `custom-controls` folder that will render the content:

```
/**
 * Custom control for arbitarty text, extend the WP customizer
 *
 */
if ( ! class_exists( 'WP_Customize_Control' ) ) {
    return NULL;
}

class Customizer_Library_Help_Text extends WP_Customize_Control {

    /**
     * Render the control's content.
     *
     */
    public function render_content() {

        echo '<span class="customize-control-title">' . esc_html( $this->label ) . '</span>';
        echo '<p class="description">' . $this->description . '</p>';
        echo '<hr />';

    }

}
```

Add the helptext case to our options switch in `interface.php`:

```
case 'helptext':

	$wp_customize->add_control(
		new Customizer_Library_Help_Text(
			$wp_customize,
			$option['id'], array(
				'label'             => $option['label'],
				'section'           => $option['section'],
				'priority'          => $option['priority'],
				'description'       => $option['description']
			)
		)
	);

break;
```

Apply the option in your section in `customizer-options.php`:

```
$options['arbitrary-text-header'] = array(
    'id' => 'arbitrary-text-header',
    'section'     => $section,
    'label'         => __( 'Text Label', 'your-theme' ),
    'type'          => 'helptext',
    'description'   	=> __( 'Example of more decription text', 'your-theme' ),
    'priority' => '5',
);
```

Style can be added by enqueueing a stylesheet with `customize_controls_enqueue_scripts`.

**Comment by devinsays** [comment]
Thanks for posting your method @jamigibbs. If the goal is to make this as flexible as possible, I think it would be better to output the HTML/content without wrapping it in any markup. What do you think about this approach.

### Custom Control

~~~php
<?php
/**
 * Add controls for arbitrary heading, description, line
 *
 * @package 	Customizer_Library
 * @author		Devin Price
 */

if ( ! class_exists( 'WP_Customize_Control' ) ) {
	return NULL;
}

class Customizer_Library_Content extends WP_Customize_Control {

	/**
	 * Render the control's content.
	 *
	 * Allows the content to be overriden without having to rewrite the wrapper.
	 *
	 * @since   1.0.0
	 * @return  void
	 */
	public function render_content() {

		switch ( $this->type ) {

			case 'content' :

				if ( isset( $this->label ) ) {
					echo '<span class="customize-control-title">' . $this->label . '</span>';
				}

				if ( isset( $this->input_attrs['content'] ) ) {
					echo $this->input_attrs['content'];
				}

				if ( isset( $this->description ) ) {
					echo '<span class="description customize-control-description">' . $this->description . '</span>';
				}

				if ( isset( $this->input_attrs['divider'] ) ) {
					echo '<hr>';
				}

				break;

			case 'divider' :
				echo '<hr>';
				break;

		}

	}

}
~~~

### Example "Option"

~~~php
$options['example-content'] = array(
	'id' => 'example-content',
	'label' => __( 'Example Content', 'textdomain' ),
	'section' => $section,
	'type' => 'content',
	'input_attrs' => array(
		'content' => __( '<p>Content to output. Use <a href="#">HTML</a> if you like.</p>', 'textdomain' ),
		'divider' => true
	),
	'description' => __( 'Optional: Example Description.', 'textdomain' )
);
~~~

**Comment by mattwiebe** [comment]
> Using "input_attrs" feels a bit janky, but arbitrary params like "content" aren't otherwise whitelisted and passed to the control by default

You whitelist a param by declaring it in the class:

```php

class Customizer_Library_Content extends WP_Customize_Control {

  // This makes your $args param whitelist a 'content` param
  public $content = '';

  /* etc */
}
```

**Comment by jamigibbs** [comment]
Lovely solution. Minor feedback: if you're going to use 'true' to fill the divider variable in the option, users will assume 'false' is the value to remove that output when in fact it's NULL because you're using isset.

**Comment by devinsays** [comment]
Thanks @mattwiebe! That piece doesn't seem especially well documented.

@jamigibbs I'm now thinking about just using a "label", "content" and "description" param. If someone wants the line break, they can just insert it as html in "content". Or do you think it is a really common use-case that should be kept?

**Comment by jamigibbs** [comment]
Agreed. Line breaks can be added within the content if needed.

**Comment by devinsays** [comment]
Thanks for all the feedback. This is now committed:

~~~php
$options['example-content'] = array(
	'id' => 'example-content',
	'label' => __( 'Example Content', 'textdomain' ),
	'section' => $section,
	'type' => 'content',
	'content' => '<p>' . __( 'Content to output. Use <a href="#">HTML</a> if you like.', 'textdomain' ) . '</p>',
	'description' => __( 'Optional: Example Description.', 'textdomain' )
);
~~~
