### ISSUE TITLE
How to check that settings are being sanitized

### ISSUE THREAD

**Issue by grappler** [devinsays/customizer-library#27]
I am doing a theme review. How can I check that the settings are being sanitized?

**Comment by devinsays** [comment]
Hi. All settings get sanitized by default. If they haven't explicitly defined one, here's where it gets set: https://github.com/devinsays/customizer-library/blob/master/extensions/interface.php#L56.

Here's the sanitization that is used:
https://github.com/devinsays/customizer-library/blob/master/extensions/interface.php#L257

Feel free to cc in the ticket if you'd like me to take a second look (to make sure nothing was modified).

If you see anything I've missed, please open an issue here.

**Comment by grappler** [comment]
Thanks!
