### ISSUE TITLE
Request to add tags to new versions

### ISSUE THREAD

**Issue by hchouhan** [devinsays/customizer-library#29]
Hello Devin, I noticed you have tagged your versions but was not able to find it in https://github.com/devinsays/customizer-library/releases. Any reason for this? If none, I'd request you to please add the versions there whenever you get time. Makes it sometimes easier to pull it.

**Comment by devinsays** [comment]
I'll try to be better about this. Tagged the latest release:
https://github.com/devinsays/customizer-library/releases

**Comment by hchouhan** [comment]
Thank you for your efforts @devinsays.
