### ISSUE TITLE
Problem when saving choices control

### ISSUE THREAD

**Issue by satrya** [devinsays/customizer-library#32]
Hi Devin,
I've strange experience with the choices control(select, radio), when saving it, it didn't worked

![choices control](https://dl.dropboxusercontent.com/u/4357218/customizer.gif)

Here's my code
```
// Radio Button
$section = $prefix . 'radio';

$sections[] = array(
	'id'          => $section,
	'title'       => __( 'Radio Section', 'standard' ),
	'priority'    => 45,
	'panel'       => $test_panel,
);
$options['test-radio'] = array(
	'id'           => $prefix . 'test_radio',
	'label'        => __( 'This is title', 'standard' ),
	'description'  => __( 'This is description', 'standard' ),
	'section'      => $section,
	'type'         => 'radio',
	'default'      => 'options2',
	'choices'      => array(
		'options1' => 'Option 1',
		'options2' => 'Option 2',
		'options3' => 'Option 3'
	)
);
```

I tried to check the sanitization code `customizer_library_sanitize_choices` and tried to remove whole code except `return $value;` and the issue disappear(saving works). Do you know what is wrong?

Thank you.

**Comment by devinsays** [comment]
Have you tested with demo library? https://github.com/devinsays/customizer-library-demo

I assume the select works there... Try copying that example over and see if any syntax is different.

**Comment by satrya** [comment]
Oh, I found the problem.
So the `$options['test-radio']` should be the same as id `'id'=> $prefix . 'test_radio',`, right?

**Comment by satrya** [comment]
I'll close it. But please answer my question above ;)

Thank you Devin

**Comment by devinsays** [comment]
You don't need to prefix it since this is saved as a theme_mod by default. I'd only prefix if you were trying to save as a setting. The ID shouldn't matter for saving, only for fetching (to make sure you get the correctly saved mod).

**Comment by satrya** [comment]
I see, thank you once again!

By the way, do you think to add more control? I'm done with some custom control like select2, category selectbox, tag selectbox, etc. If you think it'd be useful, I'll do a PR
