### ISSUE TITLE
Handle ads option

### ISSUE THREAD

**Issue by satrya** [devinsays/customizer-library#34]
Devin,
How do you handle option for ads? If I use textarea with default sanitization, it will strip the ads code, for example from adsense?

My solution for now is just create custom sanitization with 'unsafe' filter, using `stripslashes` only. I need second opinion about this.

Thank you

**Comment by devinsays** [comment]
Yeah, I think if you're offering a way to save scripts, there's not much that can be done on the sanitization front. You just need to make sure WordPress really trusts that user. edit_options is a pretty high capability. You could also do a check for current_user_can( 'unfiltered_html' ).
